# template version 2022.1

services:
  build_3.10.2-alpine3.15:
    image: python:3.10.2-alpine3.15
    working_dir: /workspace
    entrypoint:
      - /bin/sh
      - build.sh
    volumes:
      - ./:/workspace
  build_3.9.7-alpine3.14:
    image: python:3.9.7-alpine3.14
    working_dir: /workspace
    entrypoint:
      - /bin/sh
      - build.sh
    volumes:
      - ./:/workspace
